Experiment - 8
Introduction to Numpy
Jai Pratap
ENTC A3
PRN - 25070123056

In [1]:
# Import NumPy library
import numpy as np


In [2]:
# Creating arrays
a = np.array([10, 20, 30, 40])
b = np.array([[1, 2, 3],
              [4, 5, 6]])

print("Array A:", a)
print("Array B:\n", b)


Array A: [10 20 30 40]
Array B:
 [[1 2 3]
 [4 5 6]]


In [3]:
# Checking dimensions of arrays

print("Dimension of Array A:", a.ndim)
print("Dimension of Array B:", b.ndim)



Dimension of Array A: 1
Dimension of Array B: 2


In [4]:
# Display shape (rows, columns)

print("Shape of Array A:", a.shape)
print("Shape of Array B:", b.shape)



Shape of Array A: (4,)
Shape of Array B: (2, 3)


In [5]:
# Checking data types of elements

print("Data type of elements in A:", a.dtype)
print("Data type of elements in B:", b.dtype)

Data type of elements in A: int64
Data type of elements in B: int64


In [6]:
# Creating a zero matrix

zero_matrix = np.zeros((3, 4))
print(zero_matrix)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:

# Creating a matrix filled with ones

ones_matrix = np.ones((2, 3))
print(ones_matrix)



[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:

# Creating an identity matrix

identity_matrix = np.eye(3)
print(identity_matrix)



[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
# Creating array using arange()

range_array = np.arange(1, 11, 2)
print(range_array)


[1 3 5 7 9]


In [10]:
# Performing arithmetic operations

c = a * 2
d = a + 5

print("Array A multiplied by 2:", c)
print("Array A plus 5:", d)


Array A multiplied by 2: [20 40 60 80]
Array A plus 5: [15 25 35 45]


In [11]:
# Calculating mean

print("Mean of Array A:", np.mean(a))
print("Mean of Array B:", np.mean(b))


Mean of Array A: 25.0
Mean of Array B: 3.5


In [12]:
# Calculating median

print("Median of Array A:", np.median(a))
print("Median of Array B:", np.median(b))


Median of Array A: 25.0
Median of Array B: 3.5


In [13]:
# Aggregate operations on Array A

print("Operations on Array A")
print("Maximum:", np.max(a))
print("Minimum:", np.min(a))
print("Sum:", np.sum(a))

# Aggregate operations on Array B

print("\nOperations on Array B")
print("Maximum:", np.max(b))
print("Minimum:", np.min(b))
print("Sum:", np.sum(b))



Operations on Array A
Maximum: 40
Minimum: 10
Sum: 100

Operations on Array B
Maximum: 6
Minimum: 1
Sum: 21
